// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo5maTy3Zh_schCS8b4sjywi0lGaMOQbk',
    appId: '1:105376527668:web:db963d0b6fa91c22a7e161',
    messagingSenderId: '105376527668',
    projectId: 'flutter-chat-app-9f96a',
    authDomain: 'flutter-chat-app-9f96a.firebaseapp.com',
    storageBucket: 'flutter-chat-app-9f96a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAG8hDwpqmQ3R6s2kdevPeywVbpWX423E',
    appId: '1:105376527668:android:81af9d7326c5553aa7e161',
    messagingSenderId: '105376527668',
    projectId: 'flutter-chat-app-9f96a',
    storageBucket: 'flutter-chat-app-9f96a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiiu8MFHV72yjgMwGBQETwI2mOTLp5qmQ',
    appId: '1:105376527668:ios:84c2ea1b8410cdada7e161',
    messagingSenderId: '105376527668',
    projectId: 'flutter-chat-app-9f96a',
    storageBucket: 'flutter-chat-app-9f96a.appspot.com',
    iosClientId: '105376527668-rl6vnacrvrhoqhp8i3ofdqejrr9gt68m.apps.googleusercontent.com',
    iosBundleId: 'com.canapii.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiiu8MFHV72yjgMwGBQETwI2mOTLp5qmQ',
    appId: '1:105376527668:ios:8ba2d301f07b4a9ba7e161',
    messagingSenderId: '105376527668',
    projectId: 'flutter-chat-app-9f96a',
    storageBucket: 'flutter-chat-app-9f96a.appspot.com',
    iosClientId: '105376527668-8965n89q650cgcrbpmq51qdfji7g9iig.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
